- name: Join domain with adcli
  shell: echo -n {{ sssd_ad_password}} | /usr/sbin/adcli join -U {{ sssd_ad_user }} --stdin-password {{ sssd_ad_domain }}
  args:
    creates: /etc/krb5.keytab
  notify:
    - restart sssd
