---
# tasks file for sssd_ad

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- name: Ensure required packages are installed
  package:
    name: "{{ sssd_ad_packages }}"
    state: present

- name: Manage Kerberos configuration
  template:
    src: "krb5.conf.j2"
    dest: "/etc/krb5.conf"
    mode: 0644
    owner: root
    group: root

- name: Manage SSSD configuration
  template:
    src: "sssd.conf.j2"
    dest: "/etc/sssd/sssd.conf"
    mode: 0600
    owner: root
    group: root
  notify:
  - restart sssd

- name: Update PAM with authconfig
  shell: authconfig --enablesssdauth --enablesssd --enablemkhomedir --update
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version|int < 8

- name: Join domain with adcli
  shell: set -o pipefail && echo -n {{ sssd_ad_password }} | /usr/sbin/adcli join -U {{ sssd_ad_user }} \
         --stdin-password {{ sssd_ad_adcli_options }} -D {{ sssd_ad_domain }}
  args:
    creates: /etc/krb5.keytab
  notify:
    - restart sssd

- name: Enable oddjobd
  service:
    name: oddjobd
    state: started
    enabled: yes

- import_tasks: sudo.yml
  when: sssd_ad_sudo_group is defined
