---
- name: Set mkhomedir pam config default to yes
  lineinfile:
    path: /usr/share/pam-configs/mkhomedir
    regexp: '^Default:'
    line: 'Default: yes'
  register: mkhomedir_default

- name: Remove mkhomedir from seen packages if default policy was changed.
  lineinfile:
    path: /var/lib/pam/seen
    regexp: '^mkhomedir'
    state: absent
  when: mkhomedir_default.changed

- name: Run pam-auth-update to add mkhomedir to pam files if default policy was changed.
  shell: pam-auth-update --package
  when: mkhomedir_default.changed
