---
# handlers file for sssd_ad
- name: restart sssd
  service:
    name: sssd
    enabled: yes
    state: restarted
  ignore_errors: true

- name: restart samba
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items: "{{ sssd_ad_samba_services }}"
  ignore_errors: true
