---
# handlers file for sssd_ad
- name: restart sssd
  service:
    name: sssd
    enabled: yes
    state: restarted

- name: restart oddjobd
  service:
    name: oddjobd
    enabled: yes
    state: restarted
